server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: public-service
          uri: lb://public-service   # lb:// enables load balancing through Eureka
          predicates:
            - Path=/public/** 
          filters:
            - RewritePath=/public/(?<segment>.*), /${segment}
        - id: user-service
          uri: lb://user-service   # lb:// enables load balancing through Eureka
          predicates:
            - Path=/user/** 
          filters:
            - RewritePath=/user/(?<segment>.*), /${segment}
jwt:
  secret: "mY8xVt2c+9Rz2qvG5a0F7n6KbC4WjH8pLdN0QxBv1wM="  
api:
  excluded-paths:
    - /user/register
    - /user/login
    - /user/refresh-token
    - /user/check-user
  excluded-path-prefixes:
    - /public/
