server:
  port: 9095
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            idle-timeout: 30000
            maximum-pool-size: 10
            minimum-idle: 5
        password: Sum@7615
        url: jdbc:postgresql://localhost:5432/common_service
        username: application
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
        	ddl-auto:create
    mail:
        host: smtp.gmail.com
        password: hjem ajbd lyqi vmge
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: spxamcontact@gmail.com
