server:
  port: 9095

spring:
  cloud:
    config:
      enabled: false   # disable config server if not needed

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/common_service
    username: application
    password: Sum@7615
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: spxamcontact@gmail.com
    password: hjem ajbd lyqi vmge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
