server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service
    username: application
    password: Sum@7615
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: spxamcontact@gmail.com
    password: hjem ajbd lyqi vmge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: "mY8xVt2c+9Rz2qvG5a0F7n6KbC4WjH8pLdN0QxBv1wM="
  expiration: 3600000   # 1 hour in milliseconds
